- repo: local
  hooks:
    - id: lighthouse-audit
      name: Lighthouse Audit
      entry: node run-lighthouse.js  # Your script to run Lighthouse
      language: system  # Runs the script as a system command

